version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    restart: unless-stopped
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
      - RAILS_ENV
      - SECRET_KEY_BASE
      - EDITOR
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file: .env
    links:
      - db
    volumes:
      - bundle_app:/usr/local/bundle
      - root_app:/root # for bash history etc
      - ./app:/app
    tty: true
    stdin_open: true
    command: ./docker-start
  db:
    image: postgres:9.6.8
    restart: unless-stopped
    environment:
      - PGDATA=/pgdata
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/pgdata
      - root_db:/root # for bash history etc
volumes:
  bundle_app:
  pgdata:
  root_app:
  root_db:
