source 'https://rubygems.org'
#ruby "2.3.7"
ruby "2.6.6"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.11.2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.20'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry-byebug'

  # testing
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec-activemodel-mocks'
  gem 'factory_girl_rails'
  gem 'guard-cucumber'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
end

group :test do
  gem 'shoulda-matchers', '~> 3.0'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  #gem 'geckodriver-helper'
  gem 'selenium-webdriver' # 2.53 doesn't need geckodriver, but can't use higher than firefox 47
  gem 'chromedriver-helper'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 2.0'
end

gem 'carrierwave'
gem 'fog'
gem 'fog-aws'
gem 'mini_magick'
gem 'jquery-fileupload-rails'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'autoprefixer-rails'
gem 'rails_12factor', group: :production


# Translation of user generated content
gem 'globalize', '~> 5.0.0'

# User Login
gem 'devise'
gem 'devise_invitable'
gem 'mailgun_rails'
gem 'select2-rails'

# Environment var helpers
gem "figaro"

gem "socialization", :git => 'https://github.com/union-software-cooperative/socialization.git'

gem "faye-websocket"
gem "puma", "~> 5.3.1"

gem "exception_notification"

gem 'sucker_punch', '1.6.0' # '~> 2.0' # Suspect v2 is crashing production

gem 'country_select'
