#!/bin/bash
# https://devcenter.heroku.com/articles/heroku-postgres-import-export
# run as script/clone_production_db (from www dir)

# first time? link your www directory to heroku app
# heroku git:remote -a <appname>
heroku pg:backups --app dairyworker capture
mkdir -p backup
curl -o backup/latest.dump `heroku pg:backups --app dairyworker public-url`
pg_restore --verbose --clean --no-acl --no-owner -d iufcba_development backup/latest.dump
